# Generated by Django 2.0.5 on 2018-06-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeBiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecheng', models.CharField(max_length=20)),
                ('shijian', models.CharField(max_length=6)),
                ('banji', models.CharField(max_length=10)),
                ('jiaoshi', models.CharField(max_length=10)),
            ],
        ),
    ]
