# Generated by Django 2.0.5 on 2018-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_kebiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='XueJi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=3)),
                ('chusheng', models.CharField(max_length=20)),
                ('minzu', models.CharField(max_length=5)),
                ('jiguan', models.CharField(max_length=20)),
                ('zhuzi', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
