# Generated by Django 2.0.5 on 2018-06-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_xueji'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanJi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=10)),
                ('ctno', models.CharField(max_length=20)),
                ('cnumber', models.CharField(max_length=20)),
            ],
        ),
    ]
