# Generated by Django 2.0.5 on 2018-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('blog', '0005_banji'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Illuster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illuster_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=10)),
                ('modify_time', models.CharField(max_length=2)),
            ],
        ),
    ]
